# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('divisionCourse', models.CharField(max_length=128)),
                ('yearCourse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('namePupil', models.CharField(max_length=128)),
                ('surnamePupil', models.CharField(max_length=128)),
                ('numListPupil', models.IntegerField()),
                ('pupilId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
