# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Pupil', 'verbose_name_plural': 'Pupils'},
        ),
        migrations.AddField(
            model_name='course',
            name='divisionYear',
            field=models.CharField(choices=[('1', '1er A\xf1o'), ('2', '2do A\xf1o'), ('3', '3er A\xf1o')], default='A', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupil',
            name='idCourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='divisionCourse',
            field=models.CharField(choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C')], max_length=128),
        ),
    ]
