# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20160615_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='numListPupil',
        ),
    ]
