# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_pupil_numlistpupil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('idSubject', models.AutoField(primary_key=True, serialize=False)),
                ('nameSubject', models.CharField(max_length=128)),
                ('idCourse', models.ManyToManyField(to='page.Course')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.RenameField(
            model_name='pupil',
            old_name='pupilId',
            new_name='idPupil',
        ),
    ]
