# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20160615_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PupilFollowing',
            fields=[
                ('idPF', models.AutoField(primary_key=True, serialize=False)),
                ('presencePF', models.BooleanField()),
                ('datePF', models.DateTimeField(auto_now_add=True)),
                ('idPupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Pupil')),
                ('idSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Subject')),
            ],
            options={
                'verbose_name': 'Pupil Following',
                'verbose_name_plural': 'Pupils Following',
            },
        ),
    ]
