# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_pupilfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupilfollowing',
            name='commentPF',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pupilfollowing',
            name='datePF',
            field=models.DateField(),
        ),
    ]
